; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = esp32_dev

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_filters = esp32_exception_decoder
board_build.filesystem = spiffs
board_build.partitions = min_spiffs.csv

; you may make multiple _dev environments, just remember to add the respective _release environment below
[env:esp32_dev]
extends = env
build_flags =
    ${env.build_flags}
    '-D FIRMWARE_RELEASE_NAME="esp32"' ; name used to download update

[env:esp32_v2_dev]
extends = env
build_flags =
    ${env.build_flags}
    '-D FIRMWARE_RELEASE_NAME="esp32_v2"'

[env:release]
build_flags = 
    '-D OFFICIAL_RELEASE' ; use to disable custom debug features
    '-D RELEASE_VERSION=${sysenv.version_num}'
    '-D RELEASE_TAG_NAME=${sysenv.release_tag_name}'

[env:esp32_release]
extends = env:esp32_dev
build_flags = ${env:esp32_dev.build_flags}
    ${env:release.build_flags}

[env:esp32_v2_release]
extends = env:esp32_v2_dev
build_flags = ${env:esp32_v2_dev.build_flags}
    ${env:release.build_flags}